[package]
name = "multiconnect-config"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
lazy_static = "1.5.0"
log = "0.4.27"
argh = "0.1.13"
serde = "1.0.219"
serde_yml = "0.0.12"
tokio = { version = "1.44.2", features = ["full"] }
