[package]
name = "multiconnect-config"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
log = "0.4.27"
argh = "0.1.13"
serde = "1.0.219"
serde_yml = "0.0.12"
tokio = { version = "1.45.0", features = ["full"] }
fs2 = "0.4.3"
once_cell = "1.21.3"
