name: Build Rust Apps

on:
  pull_request:
    paths:
      - 'multiconnect-daemon/**'
      - 'multiconnect-frontend/**'
      - 'multiconnect-protocol/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build-daemon:
    name: Build multiconnect-daemon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev protobuf-compiler

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build multiconnect-daemon
        working-directory: ./multiconnect-daemon
        run: |
          unset RUSTFLAGS
          cargo build
  build-frontend:
    name: Build multiconnect-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev protobuf-compiler libgtk-3-dev \
            libsoup-3.0.0 libjavascriptcoregtk-4.1-dev

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build multiconnect-frontend
        working-directory: ./multiconnect-frontend
        run: |
          unset RUSTFLAGS
          cargo build
